name = "JuliaChemScripts"
uuid = "7d5de4c4-fb45-48f4-8d3a-000295dbdee9"
authors = ["Vinicius C Port"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
